# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b3c08d43d3cdec0ef905365ebb0909fc4363631fa08a809d67a198660b344c9000cb092bbdc3294376309aca3cc259c4f3682041cd3ec28948e27afc69e39c8

test:
  secret_key_base: cbec34e96e94df204952942a59f8d27c303e810e761337eccae1496ef5a65d7d182a7fa7a3adb1a4dc9ecfcf143ef73253b788fc3e0a850ef218256e9f9b030e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
